### ISSUE TITLE
Steering broken

### ISSUE THREAD

**Issue by Klabbedi** [Klabbedi/ev3#1]
Lap: 6  
Reflective value: 55  
Error: -13  
Derivative: -43  
Last error: -13  
Integral: 7.875  
Course: 137.2925  
Steering: (40, -69)  
Pow: 40  
Pow: -69                                                                                            

Lap: 7  
Reflective value: 59  
Error: -38  
Derivative: -25  
Last error: -38  
Integral: -34.0625  
Course: 100.38125  
Steering: (40, -40)  
Pow: 40  
Pow: -40                                                                                            

Lap: 8  
Reflective value: 65  
Error: -76  
Derivative: -38  
Last error: -76  
Integral: -93.03125  
Course: 165.260625  
Steering: (40, -92)  
Pow: 40  
Pow: -92                                                                                            

Lap: 9  
Reflective value: 50  
Error: 18  
Derivative: 94  
Last error: 18  
Integral: -28.515625  
Course: -293.1296875  
Steering: (-194, 40)  
Traceback (most recent call last):  
  File "LineFollower3.py", line 111, in <module>  
    run(power, target, kp, kd, ki, direction, minRef, maxRef)  
  File "LineFollower3.py", line 103, in run  
    motor.duty_cycle_sp = pow  
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 359, in duty_cycle_sp  
    self.set_attr_int('duty_cycle_sp', value)  
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 210, in set_attr_int  
    self._set_attribute(attribute, '{0:d}'.format(int(value)))  
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 204, in _set_attribute  
    self._attribute_cache.write(abspath(self._path + '/' + attribute), value)  
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 91, in write  
    f.write(value.encode())  
IOError: [Errno 22] Invalid argument

**Comment by Klabbedi** [comment]
'Course' gives way to big reactions

**Comment by Klabbedi** [comment]
Should add error handling to steering function for 'course' values >100 and <-100 to avoid run module crashing
